
pool.plugins.meta=org.dcache.pool.repository.meta.db.BerkeleyDBMetaDataRepository
pool.tags=hostname=${host.name} zone=main

[${host.name}]
dcache.zone = main

[${host.name}/pool]

pool.name=pool-${host.name}
pool.path=/pool
pool.mover.nfs.port.min=32049
pool.mover.nfs.port.max=32049
pool.mover.xrootd.port.min=31094
pool.mover.xrootd.port.max=31094
pool.mover.http.port.min=38080
pool.mover.http.port.max=38090
pool.mover.https.port.min=38443
pool.mover.https.port.max=38453

