services:

  dcache-pool:
    image: dcache/dcache:latest
    pull_policy: never
    hostname: remote-2
    networks:
      dcache:
        ipv4_address: 172.18.0.11
      remote-net:
        ipv4_address: 11.2.0.10
    ports:
      - "8280:8280"
      - "5008:5008"
      # - "2149:2049"
    environment:
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5008
    volumes:
      - ../common/dcache.conf:/opt/dcache/etc/dcache.conf
      - ./exports:/opt/dcache/etc/exports
      - ./docker-layout.conf:/opt/dcache/etc/layouts/docker-layout.conf
      - ./data:/pool

networks:
  dcache:
    external: true
    name: dcache
  remote-net:
    name: remote-net-2
    ipam:
      config:
        - subnet: 11.2.0.0/24