services:

  dcache-core:
    image: dcache/dcache:latest
    pull_policy: never
    command: core
    environment:
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    networks:
      - dcache
    ports:
      - "8080:8080"
      - "3880:3880"
      - "22224:22224"
      # - "2049:2049"
      - "5005:5005"
    volumes:
      - ../common/dcache.conf:/opt/dcache/etc/dcache.conf
      - ./docker-layout.conf:/opt/dcache/etc/layouts/docker-layout.conf
      - ./ssh_host_rsa_key:/opt/dcache/etc/admin/ssh_host_rsa_key
      - ./authorized_keys2:/opt/dcache/etc/admin/authorized_keys2
      - ./gplazma.conf:/opt/dcache/etc/gplazma.conf
      - ./htpasswd:/opt/dcache/etc/htpasswd
      - ./multi-mapfile:/opt/dcache/etc/multi-mapfile
      - ./omnisession.conf:/opt/dcache/etc/omnisession.conf
      - ./poolmanager.conf:/opt/dcache/etc/poolmanager.conf
      - ./exports:/opt/dcache/etc/exports
      - ./billing:/var/log/dcache/billing

networks:
  dcache:
    external: true
    name: dcache
