chimera.db.user=postgres
chimera.db.password=let-me-in
chimera.db.host=pg
chimera.db.name=chimera

[core]
dcache.broker.scheme = core
dcache.zone = main

[core/admin]

[core/poolmanager]
poolmanager.setup.file=/opt/dcache/etc/poolmanager.conf

[core/pnfsmanager]
chimera.db.url=jdbc:postgresql://${chimera.db.host}/${chimera.db.name}?ApplicationName=${pnfsmanager.cell.name}

[core/cleaner-disk]
chimera.db.url=jdbc:postgresql://${chimera.db.host}/${chimera.db.name}?ApplicationName=cleaner-disk

[core/gplazma]

[core/httpd]

[core/webdav]
webdav.net.port=8080
webdav.authz.anonymous-operations=FULL
webdav.authn.basic=false
webdav.redirect.on-write=false
webdav.redirect.on-read=false

# [core/nfs]
# nfs.version=4.1
# nfs.export.file=/opt/dcache/etc/exports

[core/frontend]
frontend.authn.protocol=http
frontend.authz.anonymous-operations=FULL

[core/billing]
billing.text.dir=/var/log/dcache/billing
